### ISSUE TITLE
USER STORY: Wireframes

### ISSUE THREAD

**Issue by IzabellaLopes** [IzabellaLopes/kidlit-swap#10]
As a **Developer** I can **design wireframes** so that **I gain a clear understanding of the site's structure and theme**

## Acceptance Criteria

- [x] Create wireframes for both mobile and desktop using Balsamiq
- [x] Identify the total number of pages required

## Tasks
- [x] Task 1: Design wireframes for mobile and desktop using Balsamiq
- [x] Task 2: Plan the total number of pages needed
- [x] Task 3: Save images into a documentation/wireframe images folder

## Epic: #9

**Comment by IzabellaLopes** [comment]
Designed wireframes for both mobile and desktop platforms using Balsamiq
