### ISSUE TITLE
USER STORY: Mentor Session 2: Mid-Point Project Review

### ISSUE THREAD

**Issue by IzabellaLopes** [IzabellaLopes/kidlit-swap#3]
As a **Developer** I can **share the progress of my PP4 with my mentor** so that **I can obtain valuable feedback and guidance for the remaining phases of the project**

## Acceptance Criteria

- [x] Present midway project status and address open questions
- [x] Receive feedback and create additional tasks if needed
- [x] Discuss open bugs if they exist
- [x] Ensure clarity on the further path

## Tasks

- [x] Task 1: Demonstrate project status
- [x] Task 2: Update all documentation, code, and deployment for mentor review
- [x] Task 3: Prepare questions and bugs for discussion

## Epic: #2
