### ISSUE TITLE
USER STORY: Initial Django Set Up

### ISSUE THREAD

**Issue by IzabellaLopes** [IzabellaLopes/kidlit-swap#6]
As a **Developer** I can **set up a new Django project** so that **I can create the project's structure**

## Acceptance Criteria

- [x] The Django project is successfully initialized
- [x] A new project named "kidlit_swap" is created
- [x] Add the first app to the project's settings

## Tasks

- [x] Task 1: Initialize a new Django project
- [x] Task 2: Create a new project with the name "kidlit_swap"
- [x] Task 3: Create the first app and add it to settings.py
- [x] Task 4: Create an env.py file to hide secret keys
- [x] Task 5: Add env.py to .gitignore to keep secret keys private
- [x] Task 6: Create a new virtual environment to install packages

**Comment by IzabellaLopes** [comment]
![django install](https://github.com/IzabellaLopes/kidlit-swap/assets/131386023/ca7c03f5-200b-4b46-9e51-4f5604dbf175)

**Comment by IzabellaLopes** [comment]
Set up initial project/app and config files
