### ISSUE TITLE
USER STORY: Connect Database and Cloudinary Storage

### ISSUE THREAD

**Issue by IzabellaLopes** [IzabellaLopes/kidlit-swap#7]
As a **Developer** I can **connect the database and media storage** so that **the user's stored data is managed successfully**

## Acceptance Criteria

- [x] Django's settings are configured to connect to the database
- [x] Settings for ElephantSQL are appropriately configured
- [x] Settings for static files and media directory roots are set up
- [x] Database changes are migrated successfully

## Tasks

- [x] Task 1: Configure Django's settings to connect to the database
- [x] Task 2: Configure settings for ElephantSQL
- [x] Task 3: Configure settings for static files and media directory roots
- [x] Task 4: Migrate database changes

**Comment by IzabellaLopes** [comment]
Connect Database and get our static and media files stored on Cloudinary
