### ISSUE TITLE
USER STORY: Initial Heroku Deployment

### ISSUE THREAD

**Issue by IzabellaLopes** [IzabellaLopes/kidlit-swap#8]
As a **Developer** I can **perform an early deployment of the application to verify the functionality of the initial set up** so that **I can continue testing the application as it evolves during development**

## Acceptance Criteria

- [x] A new app is successfully created on Heroku
- [x] All secret keys are added to config vars in the client setup on Heroku
- [x] A requirements.txt file containing all required packages is created
- [x] A Procfile for Heroku with "gunicorn.wsgi" is successfully set up
- [x] The application is deployed to Heroku without errors
- [x] Any deployment-related errors are debugged and resolved

## Tasks

- [x] Task 1: Create a new app on Heroku
- [x] Task 2: Add all secret keys to config vars in the Heroku client set up
- [x] Task 3: Create a requirements.txt file with all required packages
- [x] Task 4: Create a Procfile for Heroku with "gunicorn.wsgi"
- [x] Task 5: Deploy the application to Heroku
- [x] Task 6: Debug and resolve any errors encountered during the deployment process

## Epic: #5

**Comment by IzabellaLopes** [comment]
Deployed application on Heroku website
